import { defineConfig } from 'vitepress'

// PRISM Lab lecture *notes* site (note-style weeks: W07, W08, W14, W15).
// Slide weeks stay in Slidev under courses/; this VitePress site is deployed
// to GitHub Pages under /slides/notes/ alongside them.
export default defineConfig({
  title: 'PRISM Lab Lecture Notes',
  description: 'Advanced Machine Learning — lecture notes and worked problem sets',
  lang: 'ko-KR',
  base: '/slides/notes/',
  cleanUrls: true,
  ignoreDeadLinks: true,
  markdown: {
    math: true,
  },
  themeConfig: {
    outline: { level: [2, 3], label: '목차' },
    docFooter: { prev: '이전', next: '다음' },
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Advanced Machine Learning', link: '/advanced-machine-learning-2027/' },
      { text: 'Mathematics for AI', link: '/mathematics-for-artificial-intelligence-2027/' },
    ],
    sidebar: {
      '/advanced-machine-learning-2027/': [
        {
          text: '고급기계학습',
          items: [
            { text: '개요', link: '/advanced-machine-learning-2027/' },
          ],
        },
        {
          text: '📖 강의노트 (교재)',
          collapsed: false,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-notes/' },
            { text: '1장 · 소개', link: '/advanced-machine-learning-2027/lecture-notes/chapter-01' },
            { text: '2장 · 확률 분포', link: '/advanced-machine-learning-2027/lecture-notes/chapter-02' },
            { text: '3장 · 선형 회귀 모델', link: '/advanced-machine-learning-2027/lecture-notes/chapter-03' },
            { text: '4장 · 선형 분류 모델', link: '/advanced-machine-learning-2027/lecture-notes/chapter-04' },
            { text: '5장 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-notes/chapter-05' },
            { text: '6장 · 그래프 모델', link: '/advanced-machine-learning-2027/lecture-notes/chapter-06' },
            { text: '7장 · 혼합 모델과 EM', link: '/advanced-machine-learning-2027/lecture-notes/chapter-07' },
            { text: '8장 · 근사 추정', link: '/advanced-machine-learning-2027/lecture-notes/chapter-08' },
            { text: '9장 · 표집법', link: '/advanced-machine-learning-2027/lecture-notes/chapter-09' },
            { text: '10장 · 연속 잠재 변수', link: '/advanced-machine-learning-2027/lecture-notes/chapter-10' },
            { text: '부록 · 분포·행렬·변분법·라그랑주', link: '/advanced-machine-learning-2027/lecture-notes/appendix' },
          ],
        },
        {
          text: 'Y25-W07 · 중간고사 예제 문제',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-7/' },
            { text: '문제 1 · 기본 확률 법칙', link: '/advanced-machine-learning-2027/lecture-7/problem-01' },
            { text: '문제 2 · 기댓값과 분산', link: '/advanced-machine-learning-2027/lecture-7/problem-02' },
            { text: '문제 3 · 베이지안 결정 이론', link: '/advanced-machine-learning-2027/lecture-7/problem-03' },
            { text: '문제 4 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-7/problem-04' },
            { text: '문제 5 · 라그랑제 승수법', link: '/advanced-machine-learning-2027/lecture-7/problem-05' },
            { text: '문제 6 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-7/problem-06' },
            { text: '문제 7 · 선형 판별 함수', link: '/advanced-machine-learning-2027/lecture-7/problem-07' },
            { text: '문제 8 · 확률적 분류 모델', link: '/advanced-machine-learning-2027/lecture-7/problem-08' },
            { text: '문제 9 · 라플라스 근사법', link: '/advanced-machine-learning-2027/lecture-7/problem-09' },
            { text: '문제 10 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-7/problem-10' },
            { text: '— 실습 (Python) —', link: '/advanced-machine-learning-2027/lecture-7/lab-01' },
            { text: '문제 1 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-01' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-03' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-06' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-07' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-09' },
          ],
        },
        {
          text: 'Y25-W08-C01 · 중간고사 (1분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-8-c01/' },
            { text: '문제 1 · 베이즈 정리', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-1' },
            { text: '문제 2 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-2' },
            { text: '문제 3 · 라그랑제 승수법', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-3' },
            { text: '문제 4 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-4' },
            { text: '문제 5 · 피셔 선형 판별', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-5' },
            { text: '문제 6 · 라플라스 근사법', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-6' },
            { text: '문제 7 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-7' },
            { text: '문제 1 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-1' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-3' },
            { text: '문제 4 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-4' },
            { text: '문제 5 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-5' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-6' },
          ],
        },
        {
          text: 'Y25-W08-C02 · 중간고사 (2분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-8-c02/' },
            { text: '문제 1 · 베이즈 정리', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-1' },
            { text: '문제 2 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-2' },
            { text: '문제 3 · 라그랑제 승수법', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-3' },
            { text: '문제 4 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-4' },
            { text: '문제 5 · 확률적 생성 모델', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-5' },
            { text: '문제 6 · 라플라스 근사법', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-6' },
            { text: '문제 7 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-7' },
            { text: '문제 1 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-1' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-3' },
            { text: '문제 4 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-4' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-6' },
          ],
        },
        {
          text: 'Y25-W14 · 기말고사 예제 문제',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-14/' },
            { text: '문제 1 · 그래프 모델 그리기', link: '/advanced-machine-learning-2027/lecture-14/problem-01' },
            { text: '문제 2 · 베이즈망 계산', link: '/advanced-machine-learning-2027/lecture-14/problem-02' },
            { text: '문제 3 · k-평균 군집화', link: '/advanced-machine-learning-2027/lecture-14/problem-03' },
            { text: '문제 4 · EM 알고리즘', link: '/advanced-machine-learning-2027/lecture-14/problem-04' },
            { text: '문제 5 · 변분 추론 (ELBO)', link: '/advanced-machine-learning-2027/lecture-14/problem-05' },
            { text: '문제 6 · 단일 가우시안 변분', link: '/advanced-machine-learning-2027/lecture-14/problem-06' },
            { text: '문제 7 · 거부 표집법', link: '/advanced-machine-learning-2027/lecture-14/problem-07' },
            { text: '문제 8 · 중요도 표집법', link: '/advanced-machine-learning-2027/lecture-14/problem-08' },
            { text: '문제 9 · 조각 표집법', link: '/advanced-machine-learning-2027/lecture-14/problem-09' },
            { text: '문제 10 · 주성분 분석', link: '/advanced-machine-learning-2027/lecture-14/problem-10' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-03' },
            { text: '문제 4 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-04' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-06' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-07' },
            { text: '문제 8 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-08' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-09' },
            { text: '문제 10 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-10' },
          ],
        },
        {
          text: 'Y25-W15-C01 · 기말고사 (1분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-15-c01/' },
            { text: '문제 1 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-01' },
            { text: '문제 2 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-02' },
            { text: '문제 3 · 피셔 선형 판별', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-03' },
            { text: '문제 4 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-04' },
            { text: '문제 5 · 그래프 모델 그리기', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-05' },
            { text: '문제 6 · 베이즈망 추론', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-06' },
            { text: '문제 7 · k-평균 군집화', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-07' },
            { text: '문제 8 · 변분 추론', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-08' },
            { text: '문제 9 · 거부 표집법', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-09' },
            { text: '문제 10 · 주성분 분석', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-10' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-03' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-07' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-09' },
            { text: '문제 10 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-10' },
          ],
        },
        {
          text: 'Y25-W15-C02 · 기말고사 (2분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-15-c02/' },
            { text: '문제 1 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-01' },
            { text: '문제 2 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-02' },
            { text: '문제 3 · 피셔 선형 판별', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-03' },
            { text: '문제 4 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-04' },
            { text: '문제 5 · 그래프 모델 그리기', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-05' },
            { text: '문제 6 · 베이즈망 추론', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-06' },
            { text: '문제 7 · k-평균 군집화', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-07' },
            { text: '문제 8 · 변분 추론', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-08' },
            { text: '문제 9 · 중요도 표집법', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-09' },
            { text: '문제 10 · 주성분 분석', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-10' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-03' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-07' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-09' },
            { text: '문제 10 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-10' },
          ],
        },
      ],
      '/mathematics-for-artificial-intelligence-2027/': [
        {
          text: '인공지능수학',
          items: [
            { text: '개요', link: '/mathematics-for-artificial-intelligence-2027/' },
          ],
        },
        {
          text: 'W07 · 중간고사 요약',
          collapsed: false,
          items: [
            { text: '소개', link: '/mathematics-for-artificial-intelligence-2027/lecture-7/' },
            { text: '수와 연산 · 집합 · 복소수', link: '/mathematics-for-artificial-intelligence-2027/lecture-7/numbers-and-sets' },
            { text: '함수', link: '/mathematics-for-artificial-intelligence-2027/lecture-7/functions' },
            { text: '확률', link: '/mathematics-for-artificial-intelligence-2027/lecture-7/probability' },
            { text: '통계', link: '/mathematics-for-artificial-intelligence-2027/lecture-7/statistics' },
          ],
        },
        {
          text: 'W08 · 중간고사',
          collapsed: true,
          items: [
            { text: '소개', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/' },
            { text: '문제 1 · 진법 변환', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-01' },
            { text: '문제 2 · 함수 그래프 (대칭)', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-02' },
            { text: '문제 3 · 조합 확률', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-03' },
            { text: '문제 4 · 지수방정식', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-04' },
            { text: '문제 5 · 로그 방정식', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-05' },
            { text: '문제 6 · 멱집합의 원소 개수', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-06' },
            { text: '문제 7 · 이항분포', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-07' },
            { text: '문제 8 · 가설검정', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-08' },
            { text: '문제 9 · 포아송분포', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-09' },
            { text: '문제 10 · 매클로린 급수', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-10' },
            { text: '문제 11 · 합성함수', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-11' },
            { text: '문제 12 · 분류 성능 지표', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-12' },
            { text: '문제 13 · 복소수의 근', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-13' },
            { text: '문제 14 · 집합 조건 충족 여부', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-14' },
            { text: '문제 15 · 베이즈 정리 (두 주머니)', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/problem-15' },
            { text: '문제 1 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-01' },
            { text: '문제 3 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-03' },
            { text: '문제 4 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-04' },
            { text: '문제 5 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-05' },
            { text: '문제 6 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-06' },
            { text: '문제 7 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-07' },
            { text: '문제 9 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-09' },
            { text: '문제 10 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-10' },
            { text: '문제 11 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-11' },
            { text: '문제 12 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-12' },
            { text: '문제 13 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-13' },
            { text: '문제 14 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-14' },
            { text: '문제 15 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-8/lab-15' },
          ],
        },
        {
          text: 'W14 · 기말고사 요약',
          collapsed: true,
          items: [
            { text: '소개', link: '/mathematics-for-artificial-intelligence-2027/lecture-14/' },
            { text: '선형대수 · 텐서와 행렬', link: '/mathematics-for-artificial-intelligence-2027/lecture-14/linear-algebra' },
            { text: '미분 · 도함수와 그래디언트', link: '/mathematics-for-artificial-intelligence-2027/lecture-14/differentiation' },
            { text: '행렬 미분 · 야코비와 헤시안', link: '/mathematics-for-artificial-intelligence-2027/lecture-14/matrix-calculus' },
            { text: '신경망 · 데이터 흐름', link: '/mathematics-for-artificial-intelligence-2027/lecture-14/neural-networks' },
          ],
        },
        {
          text: 'W15 · 기말고사',
          collapsed: true,
          items: [
            { text: '소개', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/' },
            { text: '문제 1 · 시그모이드 함수 그래프', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-01' },
            { text: '문제 2 · 매클로린 급수 (합성함수)', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-02' },
            { text: '문제 3 · 조건부 확률', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-03' },
            { text: '문제 4 · 로그미분법', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-04' },
            { text: '문제 5 · 몫의 미분법', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-05' },
            { text: '문제 6 · 역함수', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-06' },
            { text: '문제 7 · 복소수 방정식', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-07' },
            { text: '문제 8 · 매개변수 미분 dy/dx', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-08' },
            { text: '문제 9 · 베이즈 정리 (공장)', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-09' },
            { text: '문제 10 · 고윳값과 고유벡터', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-10' },
            { text: '문제 11 · 전치행렬', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-11' },
            { text: '문제 12 · 이계 편미분', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-12' },
            { text: '문제 13 · 그래디언트', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-13' },
            { text: '문제 14 · 행렬함수의 도함수', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-14' },
            { text: '문제 15 · 방향도함수', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-15' },
            { text: '문제 16 · 이산 합성곱', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-16' },
            { text: '문제 17 · 복소함수의 극값', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/problem-17' },
            { text: '문제 2 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-02' },
            { text: '문제 3 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-03' },
            { text: '문제 4 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-04' },
            { text: '문제 5 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-05' },
            { text: '문제 6 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-06' },
            { text: '문제 7 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-07' },
            { text: '문제 8 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-08' },
            { text: '문제 9 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-09' },
            { text: '문제 10 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-10' },
            { text: '문제 11 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-11' },
            { text: '문제 12 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-12' },
            { text: '문제 13 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-13' },
            { text: '문제 14 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-14' },
            { text: '문제 15 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-15' },
            { text: '문제 16 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-16' },
            { text: '문제 17 실습', link: '/mathematics-for-artificial-intelligence-2027/lecture-15/lab-17' },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/sswu-prism-lab/slides' },
    ],
  },
})
