import { defineConfig } from 'vitepress'

// PRISM Lab lecture *notes* site (note-style weeks: W07, W08, W14, W15).
// Slide weeks stay in Slidev under courses/; this VitePress site is deployed
// to GitHub Pages under /slides/notes/ alongside them.
export default defineConfig({
  title: 'PRISM Lab Lecture Notes',
  description: 'Advanced Machine Learning — lecture notes and worked problem sets',
  lang: 'ko-KR',
  base: '/slides/notes/',
  cleanUrls: true,
  ignoreDeadLinks: true,
  markdown: {
    math: true,
  },
  themeConfig: {
    outline: { level: [2, 3], label: '목차' },
    docFooter: { prev: '이전', next: '다음' },
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Advanced Machine Learning', link: '/advanced-machine-learning-2027/' },
    ],
    sidebar: {
      '/advanced-machine-learning-2027/': [
        {
          text: '고급기계학습',
          items: [
            { text: '개요', link: '/advanced-machine-learning-2027/' },
          ],
        },
        {
          text: '📖 강의노트 (교재)',
          collapsed: false,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-notes/' },
            { text: '1장 · 소개', link: '/advanced-machine-learning-2027/lecture-notes/chapter-01' },
            { text: '2장 · 확률 분포', link: '/advanced-machine-learning-2027/lecture-notes/chapter-02' },
            { text: '3장 · 선형 회귀 모델', link: '/advanced-machine-learning-2027/lecture-notes/chapter-03' },
            { text: '4장 · 선형 분류 모델', link: '/advanced-machine-learning-2027/lecture-notes/chapter-04' },
          ],
        },
        {
          text: 'Y25-W07 · 중간고사 예제 문제',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-7/' },
            { text: '문제 1 · 기본 확률 법칙', link: '/advanced-machine-learning-2027/lecture-7/problem-01' },
            { text: '문제 2 · 기댓값과 분산', link: '/advanced-machine-learning-2027/lecture-7/problem-02' },
            { text: '문제 3 · 베이지안 결정 이론', link: '/advanced-machine-learning-2027/lecture-7/problem-03' },
            { text: '문제 4 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-7/problem-04' },
            { text: '문제 5 · 라그랑제 승수법', link: '/advanced-machine-learning-2027/lecture-7/problem-05' },
            { text: '문제 6 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-7/problem-06' },
            { text: '문제 7 · 선형 판별 함수', link: '/advanced-machine-learning-2027/lecture-7/problem-07' },
            { text: '문제 8 · 확률적 분류 모델', link: '/advanced-machine-learning-2027/lecture-7/problem-08' },
            { text: '문제 9 · 라플라스 근사법', link: '/advanced-machine-learning-2027/lecture-7/problem-09' },
            { text: '문제 10 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-7/problem-10' },
            { text: '— 실습 (Python) —', link: '/advanced-machine-learning-2027/lecture-7/lab-01' },
            { text: '문제 1 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-01' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-03' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-06' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-07' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-7/lab-09' },
          ],
        },
        {
          text: 'Y25-W08-C01 · 중간고사 (1분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-8-c01/' },
            { text: '문제 1 · 베이즈 정리', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-1' },
            { text: '문제 2 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-2' },
            { text: '문제 3 · 라그랑제 승수법', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-3' },
            { text: '문제 4 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-4' },
            { text: '문제 5 · 피셔 선형 판별', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-5' },
            { text: '문제 6 · 라플라스 근사법', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-6' },
            { text: '문제 7 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-8-c01/problem-7' },
            { text: '문제 1 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-1' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-3' },
            { text: '문제 4 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-4' },
            { text: '문제 5 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-5' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-8-c01/lab-6' },
          ],
        },
        {
          text: 'Y25-W08-C02 · 중간고사 (2분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-8-c02/' },
            { text: '문제 1 · 베이즈 정리', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-1' },
            { text: '문제 2 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-2' },
            { text: '문제 3 · 라그랑제 승수법', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-3' },
            { text: '문제 4 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-4' },
            { text: '문제 5 · 확률적 생성 모델', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-5' },
            { text: '문제 6 · 라플라스 근사법', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-6' },
            { text: '문제 7 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-8-c02/problem-7' },
            { text: '문제 1 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-1' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-3' },
            { text: '문제 4 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-4' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-8-c02/lab-6' },
          ],
        },
        {
          text: 'Y25-W14 · 기말고사 예제 문제',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-14/' },
            { text: '문제 1 · 그래프 모델 그리기', link: '/advanced-machine-learning-2027/lecture-14/problem-01' },
            { text: '문제 2 · 베이즈망 계산', link: '/advanced-machine-learning-2027/lecture-14/problem-02' },
            { text: '문제 3 · k-평균 군집화', link: '/advanced-machine-learning-2027/lecture-14/problem-03' },
            { text: '문제 4 · EM 알고리즘', link: '/advanced-machine-learning-2027/lecture-14/problem-04' },
            { text: '문제 5 · 변분 추론 (ELBO)', link: '/advanced-machine-learning-2027/lecture-14/problem-05' },
            { text: '문제 6 · 단일 가우시안 변분', link: '/advanced-machine-learning-2027/lecture-14/problem-06' },
            { text: '문제 7 · 거부 표집법', link: '/advanced-machine-learning-2027/lecture-14/problem-07' },
            { text: '문제 8 · 중요도 표집법', link: '/advanced-machine-learning-2027/lecture-14/problem-08' },
            { text: '문제 9 · 조각 표집법', link: '/advanced-machine-learning-2027/lecture-14/problem-09' },
            { text: '문제 10 · 주성분 분석', link: '/advanced-machine-learning-2027/lecture-14/problem-10' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-03' },
            { text: '문제 4 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-04' },
            { text: '문제 6 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-06' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-07' },
            { text: '문제 8 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-08' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-09' },
            { text: '문제 10 실습', link: '/advanced-machine-learning-2027/lecture-14/lab-10' },
          ],
        },
        {
          text: 'Y25-W15-C01 · 기말고사 (1분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-15-c01/' },
            { text: '문제 1 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-01' },
            { text: '문제 2 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-02' },
            { text: '문제 3 · 피셔 선형 판별', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-03' },
            { text: '문제 4 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-04' },
            { text: '문제 5 · 그래프 모델 그리기', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-05' },
            { text: '문제 6 · 베이즈망 추론', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-06' },
            { text: '문제 7 · k-평균 군집화', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-07' },
            { text: '문제 8 · 변분 추론', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-08' },
            { text: '문제 9 · 거부 표집법', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-09' },
            { text: '문제 10 · 주성분 분석', link: '/advanced-machine-learning-2027/lecture-15-c01/problem-10' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-03' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-07' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-09' },
            { text: '문제 10 실습', link: '/advanced-machine-learning-2027/lecture-15-c01/lab-10' },
          ],
        },
        {
          text: 'Y25-W15-C02 · 기말고사 (2분반)',
          collapsed: true,
          items: [
            { text: '소개', link: '/advanced-machine-learning-2027/lecture-15-c02/' },
            { text: '문제 1 · 최대가능도추정', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-01' },
            { text: '문제 2 · 최소제곱법', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-02' },
            { text: '문제 3 · 피셔 선형 판별', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-03' },
            { text: '문제 4 · 커널 방법론', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-04' },
            { text: '문제 5 · 그래프 모델 그리기', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-05' },
            { text: '문제 6 · 베이즈망 추론', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-06' },
            { text: '문제 7 · k-평균 군집화', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-07' },
            { text: '문제 8 · 변분 추론', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-08' },
            { text: '문제 9 · 중요도 표집법', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-09' },
            { text: '문제 10 · 주성분 분석', link: '/advanced-machine-learning-2027/lecture-15-c02/problem-10' },
            { text: '문제 2 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-02' },
            { text: '문제 3 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-03' },
            { text: '문제 7 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-07' },
            { text: '문제 9 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-09' },
            { text: '문제 10 실습', link: '/advanced-machine-learning-2027/lecture-15-c02/lab-10' },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/sswu-prism-lab/slides' },
    ],
  },
})
